## Data Loading - International Football Results 1872 to 2026

Loading in data using kaggle. Data used: https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017/data

This dataset includes 49,393 results of international football matches starting from the very first official match in 1872 up to 2025. The matches range from FIFA World Cup to FIFI Wild Cup to regular friendly matches. The matches are strictly men's full internationals and the data does not include Olympic Games or matches where at least one of the teams was the nation's B-team, U-23 or a league select team.

In [167]:
import shutil
import kagglehub
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt
from pathlib import Path

DATA_DIRECTORY = Path("../data/international-football-results")

def get_data_path(data_directory:Path) -> Path:

    if data_directory.exists():
        path = data_directory
        print("Using cached dataset at:", path)
    else:
        download_path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
        data_directory.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(download_path, data_directory)
        path = data_directory
        print("Downloaded dataset to:", path)

    return path


def load_data(data_directory: Path) -> dict[str,pd.DataFrame]:
    frames = {file_path.stem : pd.read_csv(file_path) for file_path in sorted(data_directory.glob('*csv'))}

    for frame in frames.values():
        if 'date' in frame.columns:
            frame['date'] = pd.to_datetime(frame['date'],errors = 'coerce')
    
    return frames



frames = load_data(DATA_DIRECTORY)

results = frames['results']
shootouts = frames['shootouts']
goalscorers = frames['goalscorers']
former_names = frames['former_names']

In [168]:
def string_column(df,col,cardinality_threshold):
    unique_values = df[col].nunique()
    print(f'Total Unique Values in {col} = {unique_values}')
    if unique_values <= cardinality_threshold:
        print(df[col].value_counts())
    else:
        print('\n\nTop 10 Most Frequent Values')
        print(df[col].value_counts().head(10))
        print('\n\nBottom 10 Most Frequent Values')
        print(df[col].value_counts().tail(20))

def number_column(df,col):
    print(f'\n\n=== Summary Statistic {col}===')
    print(f' Max = {df[col].max():.2f}')
    print(f' Mean = {df[col].mean():.2f}')
    #print(f' Mode = {df[col].mode():.2f}')
    print(f' Median = {df[col].median():.2f}')
    print(f' Min = {df[col].min():.2f}')

def date_column(df,col):

    df = df.copy()

    print(f'\n\n=== Summary Statistic {col}===')

    print(f'Earliest Date == {df[col].min()}')
    print(f'Latest Date == {df[col].max()}')

    df['month'] = df[col].dt.month
    df['year'] = df[col].dt.year
    

    print(df[col].value_counts().head(25))

    print('\n\n',df['year'].value_counts().head(25))

    print('\n\n',df['month'].value_counts())

    #print(cross_count.to_string)

def column_review(df,col,cardinality_threshold = 100):

    nulls = (df[col].isna()).sum()
    pct_null = nulls/(len(df[col]))
    print(f'{col} has {pct_null:.1%} nulls ({nulls} out of {len(df[col]):,})')

    if pd.api.types.is_string_dtype(df[col]):
        string_column(df,col,cardinality_threshold)
    
    if pd.api.types.is_any_real_numeric_dtype(df[col]) or pd.api.types.is_float_dtype(df[col]):
        number_column(df,col)

    if pd.api.types.is_datetime64_any_dtype(df[col]):
        date_column(df,col)
        
            


def dataset_review(df,cardinality_threshold = 100):

    
    print(f'Totals Rows = {len(df)}')
    print(f'Totals Columns = {len(df.columns)}') 
    print(f'Columns = {list(df.columns)}')
    print(df.dtypes)

    print('\n\n === Example Row ===')
    print(df.iloc[-1])

    for column in df.columns:

        column_review(df,column)

In [169]:
dataset_review(results)

Totals Rows = 49477
Totals Columns = 9
Columns = ['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']
date          datetime64[us]
home_team                str
away_team                str
home_score           float64
away_score           float64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object


 === Example Row ===
date          2026-06-27 00:00:00
home_team                 Croatia
away_team                   Ghana
home_score                    NaN
away_score                    NaN
tournament         FIFA World Cup
city                 Philadelphia
country             United States
neutral                      True
Name: 49476, dtype: object
date has 0.0% nulls (0 out of 49,477)


=== Summary Statistic date===
Earliest Date == 1872-11-30 00:00:00
Latest Date == 2026-06-27 00:00:00
date
2012-02-29    66
2016-03-29    64
2025-06-10    62
2025-03-25    61
2008-03-26    60
2014-03-05    59
2023-11-21    58
2012-11-14    56
2024-03-26    56
2011-11-11    55
2022-03-29    55
2011-10-11    54
2011-11-15    54
2008-09-06    53
2008-10-11    53
2011-09-02    53
2018-10-16    53
2024-09-10    53
2011-09-06    52
2023-10-17    52
2025-11-18    52
2010-08-11    51
2013-02-06    51
2015-11-17    51
2019-09-10    51
Name: count, dtype: int64


 year
2024    1231
2019    1149
2011    1119
2021    1115
2008    1101
2004    1079
2023    1054
2000    1040
2015    1039
2001    1032
2012    1025
2025    1002
2007     988
2022     970
2013     963
2003     947
2018     929
2009     925
2017     924
2016     920
1997     907
2010     863
2014     856
2006     842
1996     837
Name: count, dtype: int64


 month
6     7496
10    5626
11    5440
9     5389
3     5244
5     3532
7     3094
8     3019
12    2846
4     2715
2     2628
1     2448
Name: count, dtype: int64
home_team has 0.0% nulls (0 out of 49,477)
Total Unique Values in home_team = 327


Top 10 Most Frequent Values
home_team
Brazil           616
Argentina        608
Mexico           605
Germany          556
England          552
South Korea      552
France           540
Sweden           535
United States    502
Hungary          499
Name: count, dtype: int64


Bottom 10 Most Frequent Values
home_team
Elba Island                  2
Yoruba Nation                2
Biafra                       2
Mapuche                      2
Central Spain                1
Western Australia            1
Sark                         1
Chechnya                     1
Kurdistan                    1
Saint Pierre and Miquelon    1
Madrid                       1
Saugeais                     1
Franconia                    1
Seborga                      1
Ryūkyū                       1
Kabylia                      1
Aymara                       1
Ticino                       1
Hmong                        1
Marshall Islands             1
Name: count, dtype: int64
away_team has 0.0% nulls (0 out of 49,477)
Total Unique Values in away_team = 321


Top 10 Most Frequent Values
away_team
Uruguay        585
Sweden         569
England        541
Hungary        507
Paraguay       497
Germany        478
Argentina      464
Poland         463
Zambia         461
South Korea    458
Name: count, dtype: int64


Bottom 10 Most Frequent Values
away_team
Chechnya              2
Western Sahara        2
Franconia             2
Yorkshire             2
Maule Sur             2
Hmong                 2
Central Spain         1
Asturias              1
Manchukuo             1
Corsica               1
Cilento               1
Andalusia             1
Quebec                1
Surrey                1
Barawa                1
Parishes of Jersey    1
Biafra                1
Aymara                1
Ticino                1
Marshall Islands      1
Name: count, dtype: int64
home_score has 0.1% nulls (44 out of 49,477)


=== Summary Statistic home_score===
 Max = 31.00
 Mean = 1.76
 Median = 1.00
 Min = 0.00
away_score has 0.1% nulls (44 out of 49,477)


=== Summary Statistic away_score===
 Max = 21.00
 Mean = 1.18
 Median = 1.00
 Min = 0.00
tournament has 0.0% nulls (0 out of 49,477)
Total Unique Values in tournament = 200


Top 10 Most Frequent Values
tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1036
Copa América                              869
African Cup of Nations                    845
AFC Asian Cup qualification               829
UEFA Nations League                       658
CECAFA Cup                                620
Name: count, dtype: int64


Bottom 10 Most Frequent Values
tournament
Tri-Nations Series                  3
Outrigger Challenge Cup             3
Four Nations' Cup                   2
Cup of Ancient Civilizations        2
Atlantic Heritage Cup               2
Marianas Cup                        2
ASEAN Championship qualification    2
Mukuru 4 Nations                    2
Tri-Nations Cup                     2
Évence Coppée Trophy                1
Open International Championship     1
Real Madrid 75th Anniversary Cup    1
FIFA 75th Anniversary Cup           1
The Other Final                     1
TIFOCO Tournament                   1
Copa Confraternidad                 1
Benedikt Fontana Cup                1
ConIFA Challenger Cup               1
CONIFA World Cup qualification      1
South Asian Super Cup               1
Name: count, dtype: int64
city has 0.0% nulls (0 out of 49,477)
Total Unique Values in city = 2089


Top 10 Most Frequent Values
city
Kuala Lumpur    745
Bangkok         580
Doha            560
London          453
Budapest        437
Kuwait City     377
Montevideo      375
Vienna          365
Oslo            359
Glasgow         356
Name: count, dtype: int64


Bottom 10 Most Frequent Values
city
Fuladshahr          1
Décines-Charpieu    1
Tekkeköy            1
Yongin              1
Qingdao             1
Talatona            1
Gabala              1
Xiamen              1
Masazir             1
Old Road Town       1
Chattanooga         1
Pawtucket           1
Chapel Hill         1
Rendall             1
Stromness           1
Karviná             1
Tarija              1
Bo                  1
Pachuca             1
Auburn              1
Name: count, dtype: int64
country has 0.0% nulls (0 out of 49,477)
Total Unique Values in country = 269


Top 10 Most Frequent Values
country
United States    1559
France            932
Malaysia          830
England           773
Qatar             760
Thailand          723
Germany           685
Sweden            654
South Africa      611
Spain             609
Name: count, dtype: int64


Bottom 10 Most Frequent Values
country
Gold Coast                  6
Saarland                    6
Manchuria                   5
Yemen AR                    5
Monaco                      5
Northern Mariana Islands    5
French Somaliland           4
Nyasaland                   4
Timor-Leste                 4
Bohemia                     3
Mandatory Palestine         3
Belgian Congo               3
New Hebrides                3
Palau                       3
Bohemia and Moravia         2
Portuguese Guinea           2
Yemen DPR                   2
Greenland                   2
Mayotte                     2
Micronesia                  1
Name: count, dtype: int64
neutral has 0.0% nulls (0 out of 49,477)

In [170]:
dataset_review(shootouts)

Totals Rows = 678
Totals Columns = 5
Columns = ['date', 'home_team', 'away_team', 'winner', 'first_shooter']
date             datetime64[us]
home_team                   str
away_team                   str
winner                      str
first_shooter               str
dtype: object


 === Example Row ===
date             2026-06-06 00:00:00
home_team                  Lithuania
away_team                     Latvia
winner                     Lithuania
first_shooter              Lithuania
Name: 677, dtype: object
date has 0.0% nulls (0 out of 678)


=== Summary Statistic date===
Earliest Date == 1967-08-22 00:00:00
Latest Date == 2026-06-06 00:00:00
date
2016-06-03    5
2024-03-26    5
1986-10-01    4
2018-06-09    4
2021-07-06    4
2026-03-30    4
2018-06-03    3
2020-10-08    3
1973-06-14    2
1973-07-26    2
1984-03-14    2
1984-12-16    2
1985-12-25    2
1986-06-21    2
1989-04-23    2
1990-12-17    2
1991-01-21    2
1995-07-17    2
1995-12-02    2
1996-06-22    2
1996-06-26    2
1996-12-21    2
1998-01-31    2
1998-02-21    2
1998-05-29    2
Name: count, dtype: int64


 year
2019    27
2022    26
2002    24
2024    24
2016    23
2004    22
2000    21
1995    18
2018    18
2023    18
1996    17
1998    17
2015    17
2021    17
1984    16
2025    16
2005    15
2011    15
1988    14
1999    14
2003    14
2006    14
2026    14
1990    13
1993    13
Name: count, dtype: int64


 month
6     135
7     121
12     70
2      54
1      47
3      46
5      42
8      41
11     38
10     36
9      30
4      18
Name: count, dtype: int64
home_team has 0.0% nulls (0 out of 678)
Total Unique Values in home_team = 188


Top 10 Most Frequent Values
home_team
South Africa    18
Thailand        15
Zambia          15
Iran            15
Senegal         13
South Korea     12
Kenya           12
Argentina       12
Uruguay         12
Ivory Coast     10
Name: count, dtype: int64


Bottom 10 Most Frequent Values
home_team
Greenland                       1
Andorra                         1
Matabeleland                    1
Tibet                           1
Panjab                          1
South Ossetia                   1
Slovakia                        1
Scotland                        1
Serbia                          1
Saint Kitts and Nevis           1
Orkney                          1
Åland Islands                   1
Solomon Islands                 1
Georgia                         1
Turks and Caicos Islands        1
Venezuela                       1
United States Virgin Islands    1
Palestine                       1
Comoros                         1
Azerbaijan                      1
Name: count, dtype: int64
away_team has 0.0% nulls (0 out of 678)
Total Unique Values in away_team = 198


Top 10 Most Frequent Values
away_team
Egypt          16
Uganda         15
South Korea    13
Argentina      11
Cameroon       11
Mali           10
Malawi         10
Spain          10
Zambia         10
Italy          10
Name: count, dtype: int64


Bottom 10 Most Frequent Values
away_team
Djibouti                        1
Northern Ireland                1
Scotland                        1
Guadeloupe                      1
Moldova                         1
Tajikistan                      1
Grenada                         1
Puerto Rico                     1
Lebanon                         1
Greenland                       1
Falkland Islands                1
Anguilla                        1
United States Virgin Islands    1
Philippines                     1
Shetland                        1
Turks and Caicos Islands        1
Yemen                           1
Bosnia and Herzegovina          1
Comoros                         1
Finland                         1
Name: count, dtype: int64
winner has 0.0% nulls (0 out of 678)
Total Unique Values in winner = 183


Top 10 Most Frequent Values
winner
South Korea     15
Argentina       15
Egypt           15
Zambia          14
Thailand        13
South Africa    13
Iraq            11
Senegal         11
Indonesia       10
Kenya           10
Name: count, dtype: int64


Bottom 10 Most Frequent Values
winner
Basque Country                  1
Raetia                          1
New Zealand                     1
Felvidék                        1
Macau                           1
Western Isles                   1
Kabylia                         1
Panjab                          1
Northern Ireland                1
Equatorial Guinea               1
Guyana                          1
Puerto Rico                     1
Georgia                         1
Anguilla                        1
United States Virgin Islands    1
Vanuatu                         1
Palestine                       1
Comoros                         1
Azerbaijan                      1
Lithuania                       1
Name: count, dtype: int64
first_shooter has 62.2% nulls (422 out of 678)
Total Unique Values in first_shooter = 96
first_shooter
Colombia               11
Italy                  10
Brazil                  9
Argentina               8
Uruguay                 8
                       ..
Oman                    1
Yemen                   1
Comoros                 1
Azerbaijan              1
Trinidad and Tobago     1
Name: count, Length: 96, dtype: int64

In [171]:
dataset_review(goalscorers)

Totals Rows = 47690
Totals Columns = 8
Columns = ['date', 'home_team', 'away_team', 'team', 'scorer', 'minute', 'own_goal', 'penalty']
date         datetime64[us]
home_team               str
away_team               str
team                    str
scorer                  str
minute              float64
own_goal               bool
penalty                bool
dtype: object


 === Example Row ===
date            2026-06-18 00:00:00
home_team               Switzerland
away_team    Bosnia and Herzegovina
team         Bosnia and Herzegovina
scorer                 Ermin Mahmić
minute                         90.0
own_goal                      False
penalty                       False
Name: 47689, dtype: object
date has 0.0% nulls (0 out of 47,690)


=== Summary Statistic date===
Earliest Date == 1916-07-02 00:00:00
Latest Date == 2026-06-18 00:00:00
date
2011-10-11    145
2008-10-11    136
2008-09-06    135
2023-11-16    135
2004-09-08    132
2004-10-13    128
2011-09-02    125
2011-09-06    123
2011-10-07    122
2004-11-17    118
2012-10-16    118
2008-09-10    117
2015-11-17    116
2013-10-15    113
2012-09-11    111
2004-10-09    110
2019-10-10    109
2024-06-11    108
2011-11-15    107
2009-10-10    104
2015-10-13    104
2005-10-08    102
2013-09-06    102
2009-09-09    101
2012-10-12    101
Name: count, dtype: int64


 year
2021    2073
2001    1747
2025    1678
2004    1655
2024    1649
2019    1568
2015    1511
1997    1355
2011    1328
2008    1293
2000    1143
2023    1130
1993    1128
2013    1126
2005    1077
2007    1024
2016    1006
2017     985
1996     978
2009     965
2022     923
2012     869
2003     719
1989     625
1985     606
Name: count, dtype: int64


 month
6     9851
10    7835
9     6771
11    5369
3     4853
7     2892
1     2077
4     2041
5     1966
2     1635
12    1331
8     1069
Name: count, dtype: int64
home_team has 0.0% nulls (0 out of 47,690)
Total Unique Values in home_team = 220


Top 10 Most Frequent Values
home_team
Brazil         1048
Argentina      1019
Germany         844
Mexico          718
Netherlands     703
Spain           694
France          689
Chile           651
Belgium         633
Italy           617
Name: count, dtype: int64


Bottom 10 Most Frequent Values
home_team
Lesotho                     27
Central African Republic    26
British Virgin Islands      25
Guam                        25
Anguilla                    24
Guadeloupe                  23
Bhutan                      23
Cook Islands                22
Comoros                     22
São Tomé and Príncipe       19
Mongolia                    19
Martinique                  19
South Sudan                 17
Timor-Leste                 15
Somalia                     14
Eritrea                      7
French Guiana                6
Yemen DPR                    5
Saarland                     4
Vietnam Republic             4
Name: count, dtype: int64
away_team has 0.0% nulls (0 out of 47,690)
Total Unique Values in away_team = 220


Top 10 Most Frequent Values
away_team
Uruguay        803
Paraguay       679
Spain          598
Germany        579
Peru           577
Chile          561
Mexico         553
Netherlands    548
Luxembourg     545
Portugal       533
Name: count, dtype: int64


Bottom 10 Most Frequent Values
away_team
British Virgin Islands      48
Aruba                       46
Dominica                    46
Guadeloupe                  46
São Tomé and Príncipe       42
Comoros                     42
Somalia                     41
Turks and Caicos Islands    40
Montserrat                  38
Brunei                      37
Burundi                     36
Chad                        33
Vietnam Republic            31
Puerto Rico                 29
Cayman Islands              28
Eritrea                     17
Yemen DPR                   15
South Sudan                 14
Saarland                     8
French Guiana                3
Name: count, dtype: int64
team has 0.0% nulls (0 out of 47,690)
Total Unique Values in team = 220


Top 10 Most Frequent Values
team
Brazil         1076
Germany        1021
Argentina       982
Spain           940
Netherlands     898
Mexico          865
Uruguay         827
England         817
France          805
Italy           761
Name: count, dtype: int64


Bottom 10 Most Frequent Values
team
Mongolia                        11
Bhutan                          11
Guam                            11
São Tomé and Príncipe           10
American Samoa                  10
Vietnam Republic                 9
United States Virgin Islands     9
Cayman Islands                   9
British Virgin Islands           8
Seychelles                       8
Turks and Caicos Islands         7
Somalia                          6
Timor-Leste                      6
Brunei                           5
South Sudan                      5
Saarland                         4
Yemen DPR                        4
Eritrea                          4
Anguilla                         3
French Guiana                    2
Name: count, dtype: int64
scorer has 0.1% nulls (48 out of 47,690)
Total Unique Values in scorer = 15352


Top 10 Most Frequent Values
scorer
Cristiano Ronaldo      121
Harry Kane              71
Robert Lewandowski      69
Lionel Messi            66
Romelu Lukaku           64
Edin Džeko              58
Aleksandar Mitrović     52
Luis Suárez             51
Ali Daei                49
Miroslav Klose          48
Name: count, dtype: int64


Bottom 10 Most Frequent Values
scorer
Axel Tuanzebe            1
Gustaf Lagerbielke       1
Julián Quiñones          1
Jovo Lukić               1
Damián Bobadilla         1
Maurício                 1
Giovanni Reyna           1
Miro Muheim              1
Nico Schlotterbeck       1
Nathaniel Brown          1
Crysencio Summerville    1
Omar Rekik               1
Emam Ashour              1
Mohamed Hany             1
Abdulelah Al-Amri        1
Caleb Yirenkyi           1
Jaminton Campaz          1
Mohamed Manai            1
Michal Sadílek           1
Ermin Mahmić             1
Name: count, dtype: int64
minute has 0.5% nulls (256 out of 47,690)


=== Summary Statistic minute===
 Max = 122.00
 Mean = 50.06
 Median = 51.00
 Min = 1.00
own_goal has 0.0% nulls (0 out of 47,690)
penalty has 0.0% nulls (0 out of 47,690)

In [ ]:
len(results[results['home_score'].isna()])

not_played = results[results['home_score'].isna()]
played = results[~results['home_score'].isna()]

played = played.assign(shootout_id = played[['date','home_team','away_team']].apply(
    lambda row: '_'.join([str(each) for each in row]), axis = 1
))

shootouts = shootouts.assign(shootout_id = shootouts[['date','home_team','away_team']].apply(
    lambda row: '_'.join([str(each) for each in row]), axis = 1
))

shootouts_ids = list(shootouts['shootout_id'].unique())

shootout_dict = pd.Series(shootouts['winner'].values, index = shootouts['shootout_id']).to_dict()

matches_with_shootouts = played[played['shootout_id'].isin(shootouts_ids)]

matches_with_shootouts = list(matches_with_shootouts['shootout_id'].unique())

print(len(shootouts_ids),len(matches_with_shootouts))

print(set(shootouts_ids)-set(matches_with_shootouts))


played['shootout_winner'] = played['shootout_id'].map(shootout_dict)

678 677
{'2011-06-29 00:00:00_Saare County_Åland Islands'}

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,shootout_id,shootout_winner
7124,1967-08-22,India,Taiwan,1.0,1.0,Merdeka Tournament,Kuala Lumpur,Malaysia,True,1967-08-22 00:00:00_India_Taiwan,Taiwan
8634,1971-11-14,South Korea,Vietnam Republic,1.0,1.0,King's Cup,Bangkok,Thailand,True,1971-11-14 00:00:00_South Korea_Vietnam Republic,South Korea
8819,1972-05-07,South Korea,Iraq,0.0,0.0,AFC Asian Cup,Bangkok,Thailand,True,1972-05-07 00:00:00_South Korea_Iraq,Iraq
8838,1972-05-17,Thailand,South Korea,1.0,1.0,AFC Asian Cup,Bangkok,Thailand,False,1972-05-17 00:00:00_Thailand_South Korea,South Korea
8841,1972-05-19,Thailand,Cambodia,2.0,2.0,AFC Asian Cup,Bangkok,Thailand,False,1972-05-19 00:00:00_Thailand_Cambodia,Thailand
...,...,...,...,...,...,...,...,...,...,...,...
49212,2026-03-30,Gabon,Trinidad and Tobago,2.0,2.0,FIFA Series,Tashkent,Uzbekistan,True,2026-03-30 00:00:00_Gabon_Trinidad and Tobago,Gabon
49213,2026-03-30,Uzbekistan,Venezuela,0.0,0.0,FIFA Series,Tashkent,Uzbekistan,False,2026-03-30 00:00:00_Uzbekistan_Venezuela,Uzbekistan
49252,2026-03-31,Bosnia and Herzegovina,Italy,1.0,1.0,FIFA World Cup qualification,Zenica,Bosnia and Herzegovina,False,2026-03-31 00:00:00_Bosnia and Herzegovina_Italy,Bosnia and Herzegovina
49255,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False,2026-03-31 00:00:00_Czech Republic_Denmark,Czech Republic
49364,2026-06-06,Lithuania,Latvia,1.0,1.0,Baltic Cup,Kaunas,Lithuania,False,2026-06-06 00:00:00_Lithuania_Latvia,Lithuania

In [212]:
played['goal_diff'] = np.abs(played['home_score']-played['away_score'])
played['year'] = played['date'].dt.year
played_long = played.melt(
    id_vars=['date','year','tournament'],
    value_vars=['home_team','away_team'],
    value_name='team'
)


wc_matches = played_long[(played_long['tournament'] == 'FIFA World Cup') & (played_long['year'] == 2026)]
wc_teams = wc_matches['team'].unique()
wc_former_names = former_names[former_names['current'].isin(wc_teams)]

name_map = dict(zip(wc_former_names['former'], wc_former_names['current']))

played['home_team'] = played['home_team'].replace(name_map)
played['away_team'] = played['away_team'].replace(name_map)

match_conditions = [
    played['home_score'] > played['away_score'],
    played['home_score'] < played['away_score'],
    played['shootout_winner'] == played['home_team'],
    played['shootout_winner'] == played['away_team']
]  

choices = ['W','L','W','L']
played['result'] = np.select(match_conditions,choices,default='D')

In [232]:
current_champion = None
reign_log = []

for row in played.itertuples(index = True,name='Match'):
    
    if current_champion is not None and current_champion not in (row.home_team, row.away_team):
        continue
    
    if row.result == 'W':
        challenger = row.home_team
    elif row.result == 'L':
        challenger = row.away_team
    else:
        continue

    if challenger != current_champion:
        reign_log.append({
            'date':row.date,
            'new_champion':challenger,
            'previous_champion':current_champion
        })
        current_champion = challenger

reigns = pd.DataFrame(reign_log)
reigns['reign_start'] = pd.to_datetime(reigns['date'])
reigns['reign_end'] = reigns['reign_start'].shift(-1)
reigns['reign_end'] = reigns['reign_end'].fillna(played['date'].max())
reigns['days_reign'] = (reigns['reign_end'] - reigns['reign_start']).dt.days

reigns

,date,new_champion,previous_champion,reign_start,reign_end,days_reign
0,1873-03-08,England,NaN,1873-03-08,1874-03-07,364
1,1874-03-07,Scotland,England,1874-03-07,1879-04-05,1855
2,1879-04-05,England,Scotland,1879-04-05,1880-03-13,343
3,1880-03-13,Scotland,England,1880-03-13,1888-03-17,2926
4,1888-03-17,England,Scotland,1888-03-17,1889-04-13,392
5,1889-04-13,Scotland,England,1889-04-13,1891-04-04,721
6,1891-04-04,England,Scotland,1891-04-04,1896-04-04,1827
7,1896-04-04,Scotland,England,1896-04-04,1898-04-02,728
8,1898-04-02,England,Scotland,1898-04-02,1900-04-07,735
9,1900-04-07,Scotland,England,1900-04-07,1903-03-21,1078
10,1903-03-21,Northern Ireland,Scotland,1903-03-21,1904-03-12,357
11,1904-03-12,England,Northern Ireland,1904-03-12,1906-04-07,756
12,1906-04-07,Scotland,England,1906-04-07,1907-03-04,331
13,1907-03-04,Wales,Scotland,1907-03-04,1908-03-07,369
14,1908-03-07,Scotland,Wales,1908-03-07,1909-03-01,359
15,1909-03-01,Wales,Scotland,1909-03-01,1909-03-15,14
16,1909-03-15,England,Wales,1909-03-15,1910-04-02,383
17,1910-04-02,Scotland,England,1910-04-02,1913-04-05,1099
18,1913-04-05,England,Scotland,1913-04-05,1914-02-14,315
19,1914-02-14,Northern Ireland,England,1914-02-14,1920-03-13,2219
20,1920-03-13,Scotland,Northern Ireland,1920-03-13,1920-04-10,28
21,1920-04-10,England,Scotland,1920-04-10,1921-04-09,364
22,1921-04-09,Scotland,England,1921-04-09,1922-02-04,301
23,1922-02-04,Wales,Scotland,1922-02-04,1922-03-13,37
24,1922-03-13,England,Wales,1922-03-13,1922-04-08,26
25,1922-04-08,Scotland,England,1922-04-08,1924-02-16,679
26,1924-02-16,Wales,Scotland,1924-02-16,1925-02-14,364
27,1925-02-14,Scotland,Wales,1925-02-14,1927-04-02,777
28,1927-04-02,England,Scotland,1927-04-02,1927-10-22,203
29,1927-10-22,Northern Ireland,England,1927-10-22,1928-02-04,105
30,1928-02-04,Wales,Northern Ireland,1928-02-04,1928-10-27,266
31,1928-10-27,Scotland,Wales,1928-10-27,1930-04-05,525
32,1930-04-05,England,Scotland,1930-04-05,1931-03-28,357
33,1931-03-28,Scotland,England,1931-03-28,1931-05-16,49
34,1931-05-16,Austria,Scotland,1931-05-16,1932-12-07,571
35,1932-12-07,England,Austria,1932-12-07,1933-04-01,115
36,1933-04-01,Scotland,England,1933-04-01,1933-09-16,168
37,1933-09-16,Northern Ireland,Scotland,1933-09-16,1933-10-14,28
38,1933-10-14,England,Northern Ireland,1933-10-14,1933-11-15,32
39,1933-11-15,Wales,England,1933-11-15,1934-09-29,318
40,1934-09-29,England,Wales,1934-09-29,1935-04-06,189
41,1935-04-06,Scotland,England,1935-04-06,1936-12-02,606
42,1936-12-02,Wales,Scotland,1936-12-02,1937-11-17,350
43,1937-11-17,England,Wales,1937-11-17,1938-04-09,143
44,1938-04-09,Scotland,England,1938-04-09,1939-04-15,371
45,1939-04-15,England,Scotland,1939-04-15,1939-05-18,33
46,1939-05-18,Yugoslavia,England,1939-05-18,1939-06-04,17
47,1939-06-04,Italy,Yugoslavia,1939-06-04,1939-11-12,161
48,1939-11-12,Switzerland,Italy,1939-11-12,1940-03-31,140
49,1940-03-31,Hungary,Switzerland,1940-03-31,1941-04-06,371
50,1941-04-06,Germany,Hungary,1941-04-06,1941-04-20,14
51,1941-04-20,Switzerland,Germany,1941-04-20,1941-11-16,210
52,1941-11-16,Hungary,Switzerland,1941-11-16,1942-05-03,168
53,1942-05-03,Germany,Hungary,1942-05-03,1942-09-20,140
54,1942-09-20,Sweden,Germany,1942-09-20,1942-11-15,56
55,1942-11-15,Switzerland,Sweden,1942-11-15,1943-05-16,182
56,1943-05-16,Hungary,Switzerland,1943-05-16,1943-11-07,175
57,1943-11-07,Sweden,Hungary,1943-11-07,1945-11-25,749
58,1945-11-25,Switzerland,Sweden,1945-11-25,1946-05-11,167
59,1946-05-11,England,Switzerland,1946-05-11,1946-05-19,8
60,1946-05-19,France,England,1946-05-19,1947-05-03,349
61,1947-05-03,England,France,1947-05-03,1947-05-18,15
62,1947-05-18,Switzerland,England,1947-05-18,1947-06-08,21
63,1947-06-08,France,Switzerland,1947-06-08,1948-04-04,301
64,1948-04-04,Italy,France,1948-04-04,1948-05-16,42
65,1948-05-16,England,Italy,1948-05-16,1949-04-09,328
66,1949-04-09,Scotland,England,1949-04-09,1950-04-15,371
67,1950-04-15,England,Scotland,1950-04-15,1950-06-29,75
68,1950-06-29,United States,England,1950-06-29,1950-07-02,3
69,1950-07-02,Chile,United States,1950-07-02,1952-04-20,658
70,1952-04-20,Brazil,Chile,1952-04-20,1953-03-19,333
71,1953-03-19,Peru,Brazil,1953-03-19,1953-03-28,9
72,1953-03-28,Uruguay,Peru,1953-03-28,1954-04-10,378
73,1954-04-10,Paraguay,Uruguay,1954-04-10,1955-03-02,326
74,1955-03-02,Argentina,Paraguay,1955-03-02,1956-02-05,340
75,1956-02-05,Brazil,Argentina,1956-02-05,1956-04-25,80
76,1956-04-25,Italy,Brazil,1956-04-25,1956-06-24,60
77,1956-06-24,Argentina,Italy,1956-06-24,1957-04-06,286
78,1957-04-06,Peru,Argentina,1957-04-06,1957-04-09,3
79,1957-04-09,Argentina,Peru,1957-04-09,1957-07-10,92
80,1957-07-10,Brazil,Argentina,1957-07-10,1957-09-15,67
81,1957-09-15,Chile,Brazil,1957-09-15,1957-09-29,14
82,1957-09-29,Bolivia,Chile,1957-09-29,1957-10-27,28
83,1957-10-27,Argentina,Bolivia,1957-10-27,1958-04-06,161
84,1958-04-06,Uruguay,Argentina,1958-04-06,1958-04-30,24
85,1958-04-30,Argentina,Uruguay,1958-04-30,1958-06-08,39
86,1958-06-08,Germany,Argentina,1958-06-08,1958-06-24,16
87,1958-06-24,Sweden,Germany,1958-06-24,1958-06-29,5
88,1958-06-29,Brazil,Sweden,1958-06-29,1959-12-12,531
89,1959-12-12,Uruguay,Brazil,1959-12-12,1960-08-17,249
90,1960-08-17,Argentina,Uruguay,1960-08-17,1961-06-11,298
91,1961-06-11,Spain,Argentina,1961-06-11,1962-05-31,354
92,1962-05-31,Czechoslovakia,Spain,1962-05-31,1962-06-07,7
93,1962-06-07,Mexico,Czechoslovakia,1962-06-07,1963-03-24,290
94,1963-03-24,Curaçao,Mexico,1963-03-24,1963-03-28,4
95,1963-03-28,Costa Rica,Curaçao,1963-03-28,1963-09-04,160
96,1963-09-04,Colombia,Costa Rica,1963-09-04,1965-07-20,685
97,1965-07-20,Ecuador,Colombia,1965-07-20,1965-08-22,33
98,1965-08-22,Chile,Ecuador,1965-08-22,1966-02-23,185
99,1966-02-23,Russia,Chile,1966-02-23,1966-07-25,152
100,1966-07-25,Germany,Russia,1966-07-25,1966-07-30,5
101,1966-07-30,England,Germany,1966-07-30,1967-04-15,259
102,1967-04-15,Scotland,England,1967-04-15,1967-05-10,25
103,1967-05-10,Russia,Scotland,1967-05-10,1967-10-15,158
104,1967-10-15,Austria,Russia,1967-10-15,1968-06-16,245
105,1968-06-16,Russia,Austria,1968-06-16,1969-08-06,416
106,1969-08-06,Sweden,Russia,1969-08-06,1969-11-01,87
107,1969-11-01,France,Sweden,1969-11-01,1970-05-03,183
108,1970-05-03,Switzerland,France,1970-05-03,1970-11-15,196
109,1970-11-15,Hungary,Switzerland,1970-11-15,1971-05-19,185
110,1971-05-19,Bulgaria,Hungary,1971-05-19,1971-09-25,129
111,1971-09-25,Hungary,Bulgaria,1971-09-25,1972-01-12,109
112,1972-01-12,Spain,Hungary,1972-01-12,1973-05-02,476
113,1973-05-02,Netherlands,Spain,1973-05-02,1974-07-07,431
114,1974-07-07,Germany,Netherlands,1974-07-07,1975-03-12,248
115,1975-03-12,England,Germany,1975-03-12,1975-10-30,232
116,1975-10-30,Czechoslovakia,England,1975-10-30,1976-11-17,384
117,1976-11-17,Germany,Czechoslovakia,1976-11-17,1977-02-23,98
118,1977-02-23,France,Germany,1977-02-23,1977-03-30,35
119,1977-03-30,Republic of Ireland,France,1977-03-30,1977-06-01,63
120,1977-06-01,Bulgaria,Republic of Ireland,1977-06-01,1977-11-16,168
121,1977-11-16,France,Bulgaria,1977-11-16,1978-06-02,198
122,1978-06-02,Italy,France,1978-06-02,1978-06-21,19
123,1978-06-21,Netherlands,Italy,1978-06-21,1978-06-25,4
124,1978-06-25,Argentina,Netherlands,1978-06-25,1979-07-18,388
125,1979-07-18,Bolivia,Argentina,1979-07-18,1979-08-01,14
126,1979-08-01,Paraguay,Bolivia,1979-08-01,1979-12-05,126
127,1979-12-05,Chile,Paraguay,1979-12-05,1980-06-24,202
128,1980-06-24,Brazil,Chile,1980-06-24,1981-01-10,200
129,1981-01-10,Uruguay,Brazil,1981-01-10,1981-08-23,225
130,1981-08-23,Peru,Uruguay,1981-08-23,1982-03-23,212
131,1982-03-23,Chile,Peru,1982-03-23,1982-03-30,7
132,1982-03-30,Peru,Chile,1982-03-30,1982-06-22,84
133,1982-06-22,Poland,Peru,1982-06-22,1982-07-08,16
134,1982-07-08,Italy,Poland,1982-07-08,1982-10-27,111
135,1982-10-27,Switzerland,Italy,1982-10-27,1983-04-13,168
136,1983-04-13,Russia,Switzerland,1983-04-13,1983-11-13,214
137,1983-11-13,Portugal,Russia,1983-11-13,1984-06-02,202
138,1984-06-02,Yugoslavia,Portugal,1984-06-02,1984-06-13,11
139,1984-06-13,Belgium,Yugoslavia,1984-06-13,1984-06-16,3
140,1984-06-16,France,Belgium,1984-06-16,1985-05-02,320
141,1985-05-02,Bulgaria,France,1985-05-02,1985-09-04,125
142,1985-09-04,Netherlands,Bulgaria,1985-09-04,1985-10-16,42
143,1985-10-16,Belgium,Netherlands,1985-10-16,1985-11-20,35
144,1985-11-20,Netherlands,Belgium,1985-11-20,1986-05-14,175
145,1986-05-14,Germany,Netherlands,1986-05-14,1986-06-13,30
146,1986-06-13,Denmark,Germany,1986-06-13,1986-06-18,5
147,1986-06-18,Spain,Denmark,1986-06-18,1986-06-22,4
148,1986-06-22,Belgium,Spain,1986-06-22,1986-06-25,3
149,1986-06-25,Argentina,Belgium,1986-06-25,1987-06-10,350
150,1987-06-10,Italy,Argentina,1987-06-10,1988-06-04,360
151,1988-06-04,Wales,Italy,1988-06-04,1988-09-14,102
152,1988-09-14,Netherlands,Wales,1988-09-14,1988-11-16,63
153,1988-11-16,Italy,Netherlands,1988-11-16,1989-03-29,133
154,1989-03-29,Romania,Italy,1989-03-29,1989-04-12,14
155,1989-04-12,Poland,Romania,1989-04-12,1989-05-07,25
156,1989-05-07,Sweden,Poland,1989-05-07,1989-06-14,38
157,1989-06-14,Denmark,Sweden,1989-06-14,1989-08-23,70
158,1989-08-23,Belgium,Denmark,1989-08-23,1990-01-17,147
159,1990-01-17,Greece,Belgium,1990-01-17,1990-11-21,308
160,1990-11-21,Netherlands,Greece,1990-11-21,1992-02-12,448
161,1992-02-12,Portugal,Netherlands,1992-02-12,1992-06-03,112
162,1992-06-03,United States,Portugal,1992-06-03,1992-06-13,10
163,1992-06-13,Australia,United States,1992-06-13,1992-06-18,5
164,1992-06-18,Argentina,Australia,1992-06-18,1993-08-15,423
165,1993-08-15,Colombia,Argentina,1993-08-15,1994-04-07,235
166,1994-04-07,Bolivia,Colombia,1994-04-07,1994-04-20,13
167,1994-04-20,Romania,Bolivia,1994-04-20,1994-06-22,63
168,1994-06-22,Switzerland,Romania,1994-06-22,1994-06-26,4
169,1994-06-26,Colombia,Switzerland,1994-06-26,1995-01-31,219
170,1995-01-31,South Korea,Colombia,1995-01-31,1995-02-04,4
171,1995-02-04,Serbia,South Korea,1995-02-04,1995-05-31,116
172,1995-05-31,Russia,Serbia,1995-05-31,1996-06-11,377
173,1996-06-11,Italy,Russia,1996-06-11,1996-06-14,3
174,1996-06-14,Czech Republic,Italy,1996-06-14,1996-06-30,16
175,1996-06-30,Germany,Czech Republic,1996-06-30,1998-03-25,633
176,1998-03-25,Brazil,Germany,1998-03-25,1998-04-29,35
177,1998-04-29,Argentina,Brazil,1998-04-29,1998-07-04,66
178,1998-07-04,Netherlands,Argentina,1998-07-04,1998-07-07,3
179,1998-07-07,Brazil,Netherlands,1998-07-07,1998-07-12,5
180,1998-07-12,France,Brazil,1998-07-12,1999-06-05,328
181,1999-06-05,Russia,France,1999-06-05,2000-02-23,263
182,2000-02-23,Israel,Russia,2000-02-23,2000-04-26,63
183,2000-04-26,Czech Republic,Israel,2000-04-26,2000-06-03,38
184,2000-06-03,Germany,Czech Republic,2000-06-03,2000-06-17,14
185,2000-06-17,England,Germany,2000-06-17,2000-06-20,3
186,2000-06-20,Romania,England,2000-06-20,2000-06-24,4
187,2000-06-24,Italy,Romania,2000-06-24,2000-07-02,8
188,2000-07-02,France,Italy,2000-07-02,2001-03-28,269
189,2001-03-28,Spain,France,2001-03-28,2002-03-27,364
190,2002-03-27,Netherlands,Spain,2002-03-27,2003-09-10,532
191,2003-09-10,Czech Republic,Netherlands,2003-09-10,2004-03-31,203
192,2004-03-31,Republic of Ireland,Czech Republic,2004-03-31,2004-05-29,59
193,2004-05-29,Nigeria,Republic of Ireland,2004-05-29,2004-06-20,22
194,2004-06-20,Angola,Nigeria,2004-06-20,2005-03-27,280
195,2005-03-27,Zimbabwe,Angola,2005-03-27,2005-09-24,181
196,2005-09-24,Malawi,Zimbabwe,2005-09-24,2006-07-22,301
197,2006-07-22,Zambia,Malawi,2006-07-22,2006-10-08,78
198,2006-10-08,South Africa,Zambia,2006-10-08,2006-11-15,38
199,2006-11-15,Egypt,South Africa,2006-11-15,2007-10-17,336
200,2007-10-17,Japan,Egypt,2007-10-17,2008-03-26,161
201,2008-03-26,Bahrain,Japan,2008-03-26,2008-06-22,88
202,2008-06-22,Japan,Bahrain,2008-06-22,2008-08-20,59
203,2008-08-20,Uruguay,Japan,2008-08-20,2008-10-11,52
204,2008-10-11,Argentina,Uruguay,2008-10-11,2008-10-15,4
205,2008-10-15,Chile,Argentina,2008-10-15,2008-11-19,35
206,2008-11-19,Spain,Chile,2008-11-19,2009-06-24,217
207,2009-06-24,United States,Spain,2009-06-24,2009-06-28,4
208,2009-06-28,Brazil,United States,2009-06-28,2009-10-11,105
209,2009-10-11,Bolivia,Brazil,2009-10-11,2009-10-14,3
210,2009-10-14,Peru,Bolivia,2009-10-14,2010-10-12,363
211,2010-10-12,Panama,Peru,2010-10-12,2010-10-26,14
212,2010-10-26,Cuba,Panama,2010-10-26,2010-12-03,38
213,2010-12-03,Guadeloupe,Cuba,2010-12-03,2011-06-07,186
214,2011-06-07,Panama,Guadeloupe,2011-06-07,2011-06-22,15
215,2011-06-22,United States,Panama,2011-06-22,2011-06-25,3
216,2011-06-25,Mexico,United States,2011-06-25,2011-07-04,9
217,2011-07-04,Chile,Mexico,2011-07-04,2011-07-17,13
218,2011-07-17,Venezuela,Chile,2011-07-17,2011-07-20,3
219,2011-07-20,Paraguay,Venezuela,2011-07-20,2011-07-24,4
220,2011-07-24,Uruguay,Paraguay,2011-07-24,2012-09-07,411
221,2012-09-07,Colombia,Uruguay,2012-09-07,2013-03-26,200
222,2013-03-26,Venezuela,Colombia,2013-03-26,2013-06-11,77
223,2013-06-11,Uruguay,Venezuela,2013-06-11,2013-06-16,5
224,2013-06-16,Spain,Uruguay,2013-06-16,2013-06-30,14
225,2013-06-30,Brazil,Spain,2013-06-30,2013-08-14,45
226,2013-08-14,Switzerland,Brazil,2013-08-14,2013-11-15,93
227,2013-11-15,South Korea,Switzerland,2013-11-15,2013-11-19,4
228,2013-11-19,Russia,South Korea,2013-11-19,2014-06-22,215
229,2014-06-22,Belgium,Russia,2014-06-22,2014-07-05,13
230,2014-07-05,Argentina,Belgium,2014-07-05,2014-07-13,8
231,2014-07-13,Germany,Argentina,2014-07-13,2014-09-03,52
232,2014-09-03,Argentina,Germany,2014-09-03,2014-10-11,38
233,2014-10-11,Brazil,Argentina,2014-10-11,2015-06-17,249
234,2015-06-17,Colombia,Brazil,2015-06-17,2015-06-26,9
235,2015-06-26,Argentina,Colombia,2015-06-26,2015-07-04,8
236,2015-07-04,Chile,Argentina,2015-07-04,2015-11-17,136
237,2015-11-17,Uruguay,Chile,2015-11-17,2016-06-05,201
238,2016-06-05,Mexico,Uruguay,2016-06-05,2016-06-18,13
239,2016-06-18,Chile,Mexico,2016-06-18,2016-09-01,75
240,2016-09-01,Paraguay,Chile,2016-09-01,2016-09-06,5
241,2016-09-06,Uruguay,Paraguay,2016-09-06,2016-11-15,70
242,2016-11-15,Chile,Uruguay,2016-11-15,2017-03-23,128
243,2017-03-23,Argentina,Chile,2017-03-23,2017-03-28,5
244,2017-03-28,Bolivia,Argentina,2017-03-28,2017-08-31,156
245,2017-08-31,Peru,Bolivia,2017-08-31,2018-06-16,289
246,2018-06-16,Denmark,Peru,2018-06-16,2018-07-01,15
247,2018-07-01,Croatia,Denmark,2018-07-01,2018-07-15,14
248,2018-07-15,France,Croatia,2018-07-15,2018-11-16,124
249,2018-11-16,Netherlands,France,2018-11-16,2019-03-24,128
250,2019-03-24,Germany,Netherlands,2019-03-24,2019-09-06,166
251,2019-09-06,Netherlands,Germany,2019-09-06,2020-09-07,367
252,2020-09-07,Italy,Netherlands,2020-09-07,2021-10-06,394
253,2021-10-06,Spain,Italy,2021-10-06,2021-10-10,4
254,2021-10-10,France,Spain,2021-10-10,2022-06-03,236
255,2022-06-03,Denmark,France,2022-06-03,2022-06-10,7
256,2022-06-10,Croatia,Denmark,2022-06-10,2022-12-13,186
257,2022-12-13,Argentina,Croatia,2022-12-13,2023-11-16,338
258,2023-11-16,Uruguay,Argentina,2023-11-16,2024-03-26,131
259,2024-03-26,Ivory Coast,Uruguay,2024-03-26,2024-10-15,203
260,2024-10-15,Sierra Leone,Ivory Coast,2024-10-15,2024-11-19,35
261,2024-11-19,Zambia,Sierra Leone,2024-11-19,2025-03-25,126
262,2025-03-25,Russia,Zambia,2025-03-25,2025-11-15,235
263,2025-11-15,Chile,Russia,2025-11-15,2026-03-30,135
264,2026-03-30,New Zealand,Chile,2026-03-30,2026-06-02,64
265,2026-06-02,Haiti,New Zealand,2026-06-02,2026-06-05,3
266,2026-06-05,Peru,Haiti,2026-06-05,2026-06-08,3
267,2026-06-08,Spain,Peru,2026-06-08,2026-06-18,10

In [234]:
played[played['date'] == dt.datetime(2005,11,16)]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,shootout_id,shootout_winner,goal_diff,year,result
29639,2005-11-16,Australia,Uruguay,1.0,0.0,FIFA World Cup qualification,Sydney,Australia,False,2005-11-16 00:00:00_Australia_Uruguay,Australia,1.0,2005,W
29640,2005-11-16,Bahrain,Trinidad and Tobago,0.0,1.0,FIFA World Cup qualification,Riffa,Bahrain,False,2005-11-16 00:00:00_Bahrain_Trinidad and Tobago,NaN,1.0,2005,L
29641,2005-11-16,Cyprus,Wales,1.0,0.0,Friendly,Limassol,Cyprus,False,2005-11-16 00:00:00_Cyprus_Wales,NaN,1.0,2005,W
29642,2005-11-16,Czech Republic,Norway,1.0,0.0,FIFA World Cup qualification,Prague,Czech Republic,False,2005-11-16 00:00:00_Czech Republic_Norway,NaN,1.0,2005,W
29643,2005-11-16,Egypt,Tunisia,1.0,2.0,Friendly,Cairo,Egypt,False,2005-11-16 00:00:00_Egypt_Tunisia,NaN,1.0,2005,L
29644,2005-11-16,Georgia,Jordan,3.0,2.0,Friendly,Tbilisi,Georgia,False,2005-11-16 00:00:00_Georgia_Jordan,NaN,1.0,2005,W
29645,2005-11-16,Greece,Hungary,2.0,1.0,Friendly,Piraeus,Greece,False,2005-11-16 00:00:00_Greece_Hungary,NaN,1.0,2005,W
29646,2005-11-16,Ivory Coast,Italy,1.0,1.0,Friendly,Geneva,Switzerland,True,2005-11-16 00:00:00_Ivory Coast_Italy,NaN,0.0,2005,D
29647,2005-11-16,Japan,Angola,1.0,0.0,Friendly,Tokyo,Japan,False,2005-11-16 00:00:00_Japan_Angola,NaN,1.0,2005,W
29648,2005-11-16,South Korea,Serbia,2.0,0.0,Friendly,Seoul,South Korea,False,2005-11-16 00:00:00_South Korea_Serbia,NaN,2.0,2005,W
29649,2005-11-16,Libya,DR Congo,2.0,1.0,Friendly,Paris,France,True,2005-11-16 00:00:00_Libya_DR Congo,NaN,1.0,2005,W
29650,2005-11-16,Luxembourg,Canada,0.0,1.0,Friendly,Hesperange,Luxembourg,False,2005-11-16 00:00:00_Luxembourg_Canada,NaN,1.0,2005,L
29651,2005-11-16,Mexico,Bulgaria,0.0,3.0,Friendly,Houston,United States,True,2005-11-16 00:00:00_Mexico_Bulgaria,NaN,3.0,2005,L
29652,2005-11-16,Poland,Estonia,3.0,1.0,Friendly,Ostrowiec Świętokrzyski,Poland,False,2005-11-16 00:00:00_Poland_Estonia,NaN,2.0,2005,W
29653,2005-11-16,Qatar,Argentina,0.0,3.0,Friendly,Doha,Qatar,False,2005-11-16 00:00:00_Qatar_Argentina,NaN,3.0,2005,L
29654,2005-11-16,Romania,Nigeria,3.0,0.0,Friendly,Bucharest,Romania,False,2005-11-16 00:00:00_Romania_Nigeria,NaN,3.0,2005,W
29655,2005-11-16,Slovakia,Spain,1.0,1.0,FIFA World Cup qualification,Bratislava,Slovakia,False,2005-11-16 00:00:00_Slovakia_Spain,NaN,0.0,2005,D
29656,2005-11-16,Syria,United Arab Emirates,0.0,3.0,Friendly,Damascus,Syria,False,2005-11-16 00:00:00_Syria_United Arab Emirates,NaN,3.0,2005,L
29657,2005-11-16,Turkey,Switzerland,4.0,2.0,FIFA World Cup qualification,Istanbul,Turkey,False,2005-11-16 00:00:00_Turkey_Switzerland,NaN,2.0,2005,W

In [ ]:
#def build_elo_trend_by_team(df,team,base = 1000,runway = 30):

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,goal_diff,result,shootout_id
34873,2011-06-29,Afghanistan,Palestine,0.0,2.0,FIFA World Cup qualification,Tursunzoda,Tajikistan,True,2011,2.0,L,2011-06-29 00:00:00_Afghanistan_Palestine
34874,2011-06-29,Bangladesh,Pakistan,3.0,0.0,FIFA World Cup qualification,Dhaka,Bangladesh,False,2011,3.0,W,2011-06-29 00:00:00_Bangladesh_Pakistan
34875,2011-06-29,Cambodia,Laos,4.0,2.0,FIFA World Cup qualification,Phnom Penh,Cambodia,False,2011,2.0,W,2011-06-29 00:00:00_Cambodia_Laos
34876,2011-06-29,Iraq,Syria,1.0,2.0,Friendly,Erbil,Iraq,False,2011,1.0,L,2011-06-29 00:00:00_Iraq_Syria
34877,2011-06-29,Malaysia,Taiwan,2.0,1.0,FIFA World Cup qualification,Kuala Lumpur,Malaysia,False,2011,1.0,W,2011-06-29 00:00:00_Malaysia_Taiwan
34878,2011-06-29,Mongolia,Myanmar,1.0,0.0,FIFA World Cup qualification,Ulaanbaatar,Mongolia,False,2011,1.0,W,2011-06-29 00:00:00_Mongolia_Myanmar
34879,2011-06-29,Nepal,Timor-Leste,2.0,1.0,FIFA World Cup qualification,Kathmandu,Nepal,False,2011,1.0,W,2011-06-29 00:00:00_Nepal_Timor-Leste
34880,2011-06-29,Sri Lanka,Philippines,1.0,1.0,FIFA World Cup qualification,Colombo,Sri Lanka,False,2011,0.0,D,2011-06-29 00:00:00_Sri Lanka_Philippines
34881,2011-06-29,Vietnam,Macau,6.0,0.0,FIFA World Cup qualification,Ho Chi Minh City,Vietnam,False,2011,6.0,W,2011-06-29 00:00:00_Vietnam_Macau